/*
 Navicat Premium Dump SQL

 Source Server         : fwwb
 Source Server Type    : PostgreSQL
 Source Server Version : 160013 (160013)
 Source Host           : localhost:5432
 Source Catalog        : antifraud
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160013 (160013)
 File Encoding         : 65001

 Date: 13/04/2026 14:36:39
*/


-- ----------------------------
-- Type structure for role
-- ----------------------------
DROP TYPE IF EXISTS "public"."role";
CREATE TYPE "public"."role" AS ENUM (
  'child',
  'youth',
  'elder'
);
ALTER TYPE "public"."role" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for sources_all_data_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."sources_all_data_id_seq";
CREATE SEQUENCE "public"."sources_all_data_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for detection_results
-- ----------------------------
DROP TABLE IF EXISTS "public"."detection_results";
CREATE TABLE "public"."detection_results" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "submission_id" uuid NOT NULL,
  "risk_level" text COLLATE "pg_catalog"."default",
  "fraud_type" text COLLATE "pg_catalog"."default",
  "result_detail" jsonb,
  "created_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Table structure for detection_submissions
-- ----------------------------
DROP TABLE IF EXISTS "public"."detection_submissions";
CREATE TABLE "public"."detection_submissions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "user_id" uuid NOT NULL,
  "has_text" bool NOT NULL DEFAULT false,
  "has_audio" bool NOT NULL DEFAULT false,
  "has_image" bool NOT NULL DEFAULT false,
  "has_video" bool NOT NULL DEFAULT false,
  "text_rel_path" text COLLATE "pg_catalog"."default",
  "audio_rel_path" text COLLATE "pg_catalog"."default",
  "image_rel_path" text COLLATE "pg_catalog"."default",
  "video_rel_path" text COLLATE "pg_catalog"."default",
  "text_content" text COLLATE "pg_catalog"."default",
  "transcript" text COLLATE "pg_catalog"."default",
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "storage_batch_id" text COLLATE "pg_catalog"."default" NOT NULL,
  "text_paths" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "audio_paths" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "image_paths" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "video_paths" jsonb NOT NULL DEFAULT '[]'::jsonb
)
;

-- ----------------------------
-- Table structure for sources_all_data
-- ----------------------------
DROP TABLE IF EXISTS "public"."sources_all_data";
CREATE TABLE "public"."sources_all_data" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "data_source" text COLLATE "pg_catalog"."default",
  "sample_label" text COLLATE "pg_catalog"."default" NOT NULL,
  "fraud_type" text COLLATE "pg_catalog"."default",
  "task_type" jsonb NOT NULL,
  "content" text COLLATE "pg_catalog"."default",
  "url" text COLLATE "pg_catalog"."default",
  "audio_path" jsonb,
  "image_path" jsonb,
  "video_path" jsonb,
  "create_time" timestamp(6) NOT NULL DEFAULT now()
)
;
COMMENT ON COLUMN "public"."sources_all_data"."id" IS '主键，自增';
COMMENT ON COLUMN "public"."sources_all_data"."data_source" IS '数据来源/数据集名称，可为空';
COMMENT ON COLUMN "public"."sources_all_data"."sample_label" IS '样本黑白标签：black=黑样本，white=白样本';
COMMENT ON COLUMN "public"."sources_all_data"."fraud_type" IS '诈骗/风险类型说明（如钓鱼网站等细分类型）';
COMMENT ON COLUMN "public"."sources_all_data"."task_type" IS '任务模态，JSON 数组，元素取自 website、text、audio、image、video';
COMMENT ON COLUMN "public"."sources_all_data"."content" IS '正文内容（如网页抽取文本、话术等）';
COMMENT ON COLUMN "public"."sources_all_data"."url" IS '相关链接地址';
COMMENT ON COLUMN "public"."sources_all_data"."audio_path" IS '音频路径列表，JSON 数组，可多值';
COMMENT ON COLUMN "public"."sources_all_data"."image_path" IS '图片路径列表，JSON 数组，可多值';
COMMENT ON COLUMN "public"."sources_all_data"."video_path" IS '视频路径列表，JSON 数组，可多值';
COMMENT ON COLUMN "public"."sources_all_data"."create_time" IS '记录创建时间';

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "phone" text COLLATE "pg_catalog"."default" NOT NULL,
  "password_hash" text COLLATE "pg_catalog"."default" NOT NULL,
  "birth_date" date NOT NULL,
  "role" "public"."role" NOT NULL,
  "display_name" text COLLATE "pg_catalog"."default" NOT NULL,
  "created_at" timestamptz(6) NOT NULL DEFAULT now(),
  "updated_at" timestamptz(6) NOT NULL DEFAULT now(),
  "avatar_url" text COLLATE "pg_catalog"."default",
  "guardian_relation" text COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."sources_all_data_id_seq"
OWNED BY "public"."sources_all_data"."id";
SELECT setval('"public"."sources_all_data_id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table detection_results
-- ----------------------------
ALTER TABLE "public"."detection_results" ADD CONSTRAINT "detection_results_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table detection_submissions
-- ----------------------------
ALTER TABLE "public"."detection_submissions" ADD CONSTRAINT "detection_submissions_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Checks structure for table sources_all_data
-- ----------------------------
ALTER TABLE "public"."sources_all_data" ADD CONSTRAINT "chk_sample_label" CHECK (sample_label = ANY (ARRAY['black'::text, 'white'::text]));

-- ----------------------------
-- Primary Key structure for table sources_all_data
-- ----------------------------
ALTER TABLE "public"."sources_all_data" ADD CONSTRAINT "sources_all_data_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Uniques structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "users_phone_key" UNIQUE ("phone");

-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table detection_results
-- ----------------------------
ALTER TABLE "public"."detection_results" ADD CONSTRAINT "detection_results_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "public"."detection_submissions" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table detection_submissions
-- ----------------------------
ALTER TABLE "public"."detection_submissions" ADD CONSTRAINT "detection_submissions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION;
