/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/detect-audio` | `/detect-audio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/detect-mixed` | `/detect-mixed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/detect-text` | `/detect-text`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/detect-visual` | `/detect-visual`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/records` | `/records`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/submit` | `/submit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/records/[id]` | `/records/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/detect-audio` | `/detect-audio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/detect-mixed` | `/detect-mixed`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/detect-text` | `/detect-text`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/detect-visual` | `/detect-visual`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/records` | `/records`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/submit` | `/submit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/records/[id]` | `/records/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/detect-audio${`?${string}` | `#${string}` | ''}` | `/detect-audio${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/detect-mixed${`?${string}` | `#${string}` | ''}` | `/detect-mixed${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/detect-text${`?${string}` | `#${string}` | ''}` | `/detect-text${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/detect-visual${`?${string}` | `#${string}` | ''}` | `/detect-visual${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/records${`?${string}` | `#${string}` | ''}` | `/records${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/submit${`?${string}` | `#${string}` | ''}` | `/submit${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/detect-audio` | `/detect-audio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/detect-mixed` | `/detect-mixed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/detect-text` | `/detect-text`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/detect-visual` | `/detect-visual`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/records` | `/records`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/submit` | `/submit`; params?: Router.UnknownInputParams; } | `${'/(main)'}/records/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/records/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(main)'}/records/[id]` | `/records/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
